
name: MATLAB Simulink Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Run MATLAB Tests
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v6

      - name: MATLAB-Tests ausführen
        uses: matlab-actions/run-tests@v3
        with:
          command: run_all_tests
