name: MATLAB CI

on:           # Trigger workflow bei push und pull request -> für "main" und "master" branch   
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:      # workflow run: einer oder mehrere Jobs, einzeln oder parallel laufend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken             # Repository prüfen
        uses: actions/checkout@v4

      - name: MATLAB einrichten                 # Matlab einrichten/starten
        uses: matlab-actions/setup-matlab@v2

      - name: MATLAB-/Simulink-Tests ausführen  # Simulink testen
        uses: matlab-actions/run-command@v2
        with:
          command: "cd(getenv('MW_ORIG_WORKING_FOLDER')); disp(pwd); which run_all_tests -all; exist('tests/run_all_tests.m','file'); 
                    addpath(genpath(pwd)); run('tests/run_all_tests.m')"

      - name: Testergebnisse hochladen          # Testergebnisse sichern
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: matlab-test-results
          path: test-results/
          if-no-files-found: warn
